name: PyPi Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    env:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
      PYPI_TEST_API_KEY: ${{ secrets.PYPI_TEST_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.KIVERA_BOT_TOKEN }}
      GITUSER: kivera-bot
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 16
      - name: Setup
        run: |
          git config --global user.name "$GITUSER"
          git config --global user.email "${GITUSER}@users.noreply.github.com"
          npm install -g standard-version
          pip install twine
          envsubst < .pypirc.template > .pypirc
      - name: Build Dist
        run: |
          make dist
      - name: Git release
        run: |
          make ci-release
      - name: PyPi test release
        run: |
          make pypi-test
      - name: PyPi official release
        run: |
          make pypi
