name: PyPi Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    env:
      PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
      PYPI_TEST_API_KEY: ${{ secrets.PYPI_TEST_API_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup
        run: |
          pip install twine
          envsubst < .pypirc.template > .pypirc
      - name: Build Dist
        run: |
          python setup.py sdist
      - name: PyPi test release
        run: |
          twine upload --config-file .pypirc -r testpypi dist/kivera-sdk-*.tar.gz
      - name: PyPi official release
        run: |
          twine upload --config-file .pypirc dist/kivera-sdk-*.tar.gz
