name: Security Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:

  SynkTests:
    name: Snyk Tests
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - name: Setup
        run: |
          git config --global user.name "$GITUSER"
          git config --global user.email "${GITUSER}@users.noreply.github.com"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
      - name: Run Snyk Test
        run: |
          snyk test --fail-on=upgradable
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}